site_name: ip_info
site_description: "Queries multiple providers for information about IP addresses."
repo_url: https://github.com/DrollRobot/ip_info

theme:
  name: material
  features:
    - navigation.sections
    - navigation.expand
    - content.code.copy
    - search.highlight

nav:
  - Home: index.md
  - Reference: reference/ip_info.md

markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          paths: [src]
          options:
            docstring_style: google
            show_source: true
            show_signature_annotations: true
